<Project Sdk="Microsoft.NET.Sdk.Web">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Nullable>enable</Nullable>
    <ImplicitUsings>enable</ImplicitUsings>
    <UserSecretsId>4c551e3b-b878-4728-b6d7-1acd281a3431</UserSecretsId>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="AutoMapper" Version="$(NuGet-AutoMapper)" />
    <PackageReference Include="MassTransit" Version="$(NuGet-MassTransit)" />
    <PackageReference Include="MassTransit.AspNetCore" Version="$(NuGet-MassTransit-AspNetCore)" />
    <PackageReference Include="MassTransit.RabbitMQ" Version="$(NuGet-MassTransit-RabbitMQ)" />
    <PackageReference Include="MediatR" Version="$(NuGet-MediatR)" />
    <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="$(NuGet-Microsoft-AspNetCore-Authentication-JwtBearer)" />
    <PackageReference Include="Microsoft.Data.SqlClient" Version="$(NuGet-Microsoft-Data-SqlClient)" />
    <PackageReference Include="Microsoft.EntityFrameworkCore" Version="$(NuGet-Microsoft-EntityFrameworkCore)" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.Design" Version="$(NuGet-Microsoft-EntityFrameworkCore-Design)">
      <PrivateAssets>all</PrivateAssets>
      <IncludeAssets>runtime; build; native; contentfiles; analyzers; buildtransitive</IncludeAssets>
    </PackageReference>
    <PackageReference Include="Microsoft.EntityFrameworkCore.InMemory" Version="$(NuGet-Microsoft-EntityFrameworkCore-InMemory)" />
    <PackageReference Include="Microsoft.EntityFrameworkCore.SqlServer" Version="$(NuGet-Microsoft-EntityFrameworkCore-SqlServer)" />
    <PackageReference Include="Microsoft.VisualStudio.Azure.Containers.Tools.Targets" Version="1.15.1" />
    <PackageReference Include="Swashbuckle.AspNetCore" Version="$(NuGet-Swashbuckle-AspNetCore)" />
    <PackageReference Include="Swashbuckle.AspNetCore.SwaggerUI" Version="10.0.0" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\BrowserChat.Entity\BrowserChat.Entity.csproj" />
    <ProjectReference Include="..\BrowserChat.Util\BrowserChat.Util.csproj" />
    <ProjectReference Include="..\BrowserChat.Value\BrowserChat.Value.csproj" />
  </ItemGroup>

  <ProjectExtensions><VisualStudio><UserProperties appsettings_1json__JsonSchema="" /></VisualStudio></ProjectExtensions>

</Project>
